### ISSUE TITLE
Repository activity

### ISSUE THREAD

**Issue by DanyHenriquez** [aymerick/douceur#15]
I use this code for my mail service, but would like to know if there is any activity. I did a lot of refactoring and added Renovate to my fork.

If interested we could integrate the changes into this repo.

Is there any activity on this repo anyway? I noticed old PR's and issues that are not being replied to/merged or resolved in any way

**Comment by marwonline** [comment]
I also wanted to use this library for emails, but links are getting modified because of a bug in a used library. See here: https://github.com/PuerkitoBio/goquery/issues/448
